"use client";

import { useEffect, useState } from "react";
import {
  Image as ImageIcon,
  Video,
  Layers,
  X,
  Play,
} from "lucide-react";
import { clsx } from "clsx";

// ── Types ────────────────────────────────────────────

export interface MediaFile {
  path: string;
  model: string;
  filename: string;
}

export interface ShotMedia {
  shotId: string;
  sceneId: string;
  images: string[];
  videos: string[];
  heroImage: string | null;
  modelImages: MediaFile[];
}

// ── Component ────────────────────────────────────────

export function PreviewLightbox({
  shot,
  onClose,
}: {
  shot: ShotMedia;
  onClose: () => void;
}) {
  const [activeTab, setActiveTab] = useState<"images" | "videos" | "models">(
    shot.videos.length > 0 ? "videos" : "images",
  );
  const [selectedIndex, setSelectedIndex] = useState(0);

  // Group model images by model name for comparison view
  const modelGroups = shot.modelImages.reduce<Record<string, MediaFile[]>>((acc, img) => {
    if (!acc[img.model]) acc[img.model] = [];
    acc[img.model].push(img);
    return acc;
  }, {});
  const modelNames = Object.keys(modelGroups).sort();

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
      if (activeTab !== "models") {
        const items = activeTab === "images" ? shot.images : shot.videos;
        if (e.key === "ArrowRight") setSelectedIndex((i) => Math.min(i + 1, items.length - 1));
        if (e.key === "ArrowLeft") setSelectedIndex((i) => Math.max(i - 1, 0));
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose, activeTab, shot]);

  const currentItems = activeTab === "images" ? shot.images : activeTab === "videos" ? shot.videos : [];
  const currentPath = currentItems[selectedIndex];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm" onClick={onClose}>
      <div
        className="relative max-h-[90vh] w-full max-w-5xl rounded-2xl border border-white/[0.08] bg-bg p-4 overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="mb-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="font-mono text-sm font-bold text-white">{shot.shotId}</span>
            <span className="text-xs text-muted">{shot.sceneId}</span>
            <div className="flex rounded-lg border border-white/[0.08] overflow-hidden">
              <button
                onClick={() => { setActiveTab("images"); setSelectedIndex(0); }}
                className={clsx(
                  "flex items-center gap-1 px-2.5 py-1 text-[11px] font-medium transition-colors",
                  activeTab === "images" ? "bg-cyan/10 text-cyan" : "text-muted hover:text-white",
                )}
              >
                <ImageIcon size={10} /> Images ({shot.images.length})
              </button>
              <button
                onClick={() => { setActiveTab("videos"); setSelectedIndex(0); }}
                className={clsx(
                  "flex items-center gap-1 px-2.5 py-1 text-[11px] font-medium transition-colors",
                  activeTab === "videos" ? "bg-purple-400/10 text-purple-400" : "text-muted hover:text-white",
                )}
              >
                <Video size={10} /> Videos ({shot.videos.length})
              </button>
              {modelNames.length > 0 && (
                <button
                  onClick={() => setActiveTab("models")}
                  className={clsx(
                    "flex items-center gap-1 px-2.5 py-1 text-[11px] font-medium transition-colors",
                    activeTab === "models" ? "bg-amber-400/10 text-amber-400" : "text-muted hover:text-white",
                  )}
                >
                  <Layers size={10} /> Compare ({modelNames.length} models)
                </button>
              )}
            </div>
          </div>
          <button onClick={onClose} className="rounded-lg p-1.5 text-muted hover:bg-white/[0.06] hover:text-white transition-colors">
            <X size={16} />
          </button>
        </div>

        {/* Model comparison grid */}
        {activeTab === "models" && (
          <div className="space-y-3">
            <p className="text-[11px] text-muted">Same shot generated by different AI models — compare and choose the best</p>
            <div className="grid gap-3" style={{ gridTemplateColumns: `repeat(${Math.min(modelNames.length, 3)}, 1fr)` }}>
              {modelNames.map((model) => (
                <div key={model} className="rounded-xl border border-white/[0.06] bg-black/30 overflow-hidden">
                  <div className="border-b border-white/[0.06] px-2.5 py-1.5">
                    <span className="text-[11px] font-semibold text-amber-400">{model}</span>
                    <span className="ml-1.5 text-[10px] text-muted">{modelGroups[model].length} img</span>
                  </div>
                  <div className="space-y-1 p-1">
                    {modelGroups[model].map((img) => (
                      /* eslint-disable-next-line @next/next/no-img-element */
                      <img
                        key={img.path}
                        src={`/api/media/${img.path}`}
                        alt={`${model} - ${img.filename}`}
                        className="w-full rounded-lg object-cover"
                        loading="lazy"
                      />
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Main preview (images/videos tabs) */}
        {activeTab !== "models" && (
          <>
            <div className="flex items-center justify-center rounded-xl bg-black/40 overflow-hidden" style={{ minHeight: 400 }}>
              {currentPath ? (
                activeTab === "images" ? (
                  /* eslint-disable-next-line @next/next/no-img-element */
                  <img
                    src={`/api/media/${currentPath}`}
                    alt={shot.shotId}
                    className="max-h-[70vh] w-auto object-contain"
                  />
                ) : (
                  <video
                    key={currentPath}
                    src={`/api/media/${currentPath}`}
                    controls
                    autoPlay
                    loop
                    className="max-h-[70vh] w-auto"
                  />
                )
              ) : (
                <div className="flex flex-col items-center gap-2 py-16 text-muted">
                  {activeTab === "images" ? <ImageIcon size={32} /> : <Video size={32} />}
                  <span className="text-sm">No {activeTab} available</span>
                </div>
              )}
            </div>

            {/* Thumbnails strip */}
            {currentItems.length > 1 && (
              <div className="mt-3 flex gap-2 overflow-x-auto pb-1">
                {currentItems.map((item, idx) => {
                  const filename = item.split("/").pop() ?? item;
                  return (
                    <button
                      key={item}
                      onClick={() => setSelectedIndex(idx)}
                      className={clsx(
                        "flex-shrink-0 rounded-lg border-2 overflow-hidden transition-all",
                        idx === selectedIndex ? "border-cyan" : "border-transparent opacity-60 hover:opacity-100",
                      )}
                    >
                      {activeTab === "images" ? (
                        /* eslint-disable-next-line @next/next/no-img-element */
                        <img src={`/api/media/${item}`} alt={filename} className="h-14 w-20 object-cover" />
                      ) : (
                        <div className="flex h-14 w-20 items-center justify-center bg-white/[0.04]">
                          <Play size={14} className="text-muted" />
                          <span className="ml-1 text-[9px] text-muted">{filename.replace(/.*_/, "").replace(".mp4", "")}</span>
                        </div>
                      )}
                    </button>
                  );
                })}
              </div>
            )}

            {/* Current file info */}
            {currentPath && (
              <div className="mt-2 text-center text-[10px] text-muted">
                {currentPath.split("/").pop()} — {selectedIndex + 1}/{currentItems.length}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
